/* ============================================================
   LISTE DES PLANTES
   ------------------------------------------------------------
   Pour AJOUTER une plante : copiez un bloc { ... } ci-dessous,
   collez-le, et changez le texte. Gardez bien la virgule à la fin.

   Champs disponibles :
   - nom        : nom commun (ex: "Lavande")
   - latin      : nom scientifique (ex: "Lavandula angustifolia")
   - famille    : famille botanique (ex: "Lamiacées")
   - emoji      : un emoji qui illustre la plante (s'affiche s'il n'y a pas de photo)
   - photo      : PETITE photo pour les cartes (ex: "lavande.jpg"). Idéalement bien cadrée pour un petit format.
   - photoGrande: GRANDE photo pour le mode swipe (plein écran) et le quizz (ex: "lavande-grand.jpg").
                  Choisir une belle image où on voit bien toute la plante. Si absente, la petite photo est réutilisée.
   - lieu       : "Extérieur", "Intérieur" ou "Les deux"
   - soleil     : "Plein soleil", "Mi-ombre" ou "Ombre"
   - eau        : "Peu", "Modéré" ou "Souvent"
   - presentation: petit texte qui présente la plante (son charme, son usage) — affiché en grand dans le swipe
   - reconnaitre: comment la reconnaître (texte libre)
   - entretien  : comment l'entretenir (texte libre)
   - saison     : période de floraison / d'intérêt (texte libre)
   - floraison  : saison de floraison structurée : "Printemps", "Été", "Automne", "Hiver" ou "Toute l'année"
   - terreau    : type de terreau conseillé (universel, terre de bruyère, drainant, agrumes)
   - gel        : résistance au froid (fourchette de température), parmi 5 niveaux
   ============================================================ */

const PLANTES = [
  {
    nom: "Lavande",
    latin: "Lavandula angustifolia",
    famille: "Lamiacées",
    emoji: "💜",
    photo: "lavande.jpg",
    photoGrande: "lavande-grand.jpg",
    presentation: "Emblème de la Provence, la lavande séduit par son parfum envoûtant et ses épis d'un violet intense. Mellifère et très facile à vivre, elle structure les massifs, borde les allées et parfume aussi bien le jardin que le linge.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de juin à août",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Petit arbuste touffu aux feuilles fines, étroites et gris-vert. Tiges florales dressées portant des épis de petites fleurs violettes très parfumées. Parfum reconnaissable entre tous quand on froisse une feuille.",
    entretien: "Adore le soleil et les sols pauvres, secs et bien drainés. Craint l'excès d'eau et l'humidité stagnante. Taillez après la floraison pour garder une forme compacte. Très résistante à la sécheresse une fois installée."
  },
  {
    nom: "Olivier",
    latin: "Olea europaea",
    famille: "Oléacées",
    emoji: "🫒",
    photo: "olivier.jpg",
    photoGrande: "olivier-grand.jpg",
    presentation: "Symbole de paix et de la Méditerranée, l'olivier est un arbre presque éternel au tronc noueux plein de caractère. Rustique, graphique et persistant, il apporte une touche du Sud aussi bien en pleine terre qu'en grand pot sur une terrasse.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Feuillage persistant, fleurs au printemps",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Arbre au tronc noueux et tortueux avec l'âge. Feuilles persistantes, vert foncé dessus et argentées dessous. Petites fleurs blanches au printemps, suivies des olives en fin d'été.",
    entretien: "Plein soleil indispensable. Supporte très bien la sécheresse et les sols pauvres. Arrosez peu, surtout les premières années. Craint le gel intense et prolongé. Taille légère en fin d'hiver."
  },
  {
    nom: "Monstera",
    latin: "Monstera deliciosa",
    famille: "Aracées",
    emoji: "🌿",
    photo: "monstera.jpg",
    photoGrande: "monstera-grand.jpg",
    presentation: "Star incontestée des plantes d'intérieur, la Monstera impressionne par ses grandes feuilles découpées en forme de cœur. Facile à vivre et spectaculaire, elle crée une ambiance jungle très tendance dans n'importe quelle pièce lumineuse.",
    lieu: "Intérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Feuillage toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau universel",
    gel: "Craint le froid (à garder > 10 °C)",
    reconnaitre: "Grandes feuilles vert brillant, en forme de cœur, qui se découpent et se perforent en grandissant (les fameux « trous »). Tiges épaisses produisant des racines aériennes.",
    entretien: "Lumière vive mais sans soleil direct. Arrosez quand les premiers centimètres de terre sont secs, sans laisser d'eau stagner. Aime l'humidité ambiante : brumisez les feuilles. Tuteurez-la pour qu'elle grimpe."
  },
  {
    nom: "Rosier",
    latin: "Rosa",
    famille: "Rosacées",
    emoji: "🌹",
    photo: "rosier.jpg",
    photoGrande: "rosier-grand.jpg",
    presentation: "Reine du jardin, le rosier offre des floraisons généreuses et délicatement parfumées du printemps jusqu'aux gelées. Il en existe pour tous les goûts — buisson, tige, grimpant ou couvre-sol — et toutes les couleurs imaginables.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de mai aux gelées",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste aux tiges épineuses. Feuilles dentées composées de plusieurs folioles. Fleurs très variées en forme et en couleur, souvent parfumées.",
    entretien: "Au moins 6 h de soleil par jour. Sol riche et bien drainé. Arrosez au pied, jamais sur le feuillage, pour éviter les maladies. Taillez en fin d'hiver et retirez les fleurs fanées pour relancer la floraison."
  },
  {
    nom: "Basilic",
    latin: "Ocimum basilicum",
    famille: "Lamiacées",
    emoji: "🌱",
    photo: "basilic.jpg",
    photoGrande: "basilic-grand.jpg",
    presentation: "Incontournable du potager comme de la cuisine, le basilic embaume dès qu'on effleure ses feuilles. Cultivé en pot sur un rebord de fenêtre ou en pleine terre, il accompagne à merveille tomates, pâtes et plats d'été.",
    lieu: "Les deux",
    soleil: "Plein soleil",
    eau: "Souvent",
    saison: "De mai à septembre",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Plante aromatique aux feuilles vertes tendres, ovales et brillantes, au parfum puissant. Tiges carrées typiques des Lamiacées. Petites fleurs blanches s'il monte en graine.",
    entretien: "Beaucoup de lumière et de chaleur. Terre toujours légèrement humide, mais sans excès. Pincez régulièrement le haut des tiges pour qu'il se ramifie et retirez les fleurs pour prolonger la production de feuilles."
  },
  {
    nom: "Fougère de Boston",
    latin: "Nephrolepis exaltata",
    famille: "Nephrolépidacées",
    emoji: "🌾",
    photo: "fougere.jpg",
    photoGrande: "fougere-grand.jpg",
    presentation: "Avec ses longues frondes retombantes d'un vert tendre, la fougère de Boston apporte fraîcheur et légèreté à la maison. Très décorative en suspension, elle adore les pièces lumineuses et humides comme la salle de bains.",
    lieu: "Intérieur",
    soleil: "Ombre",
    eau: "Souvent",
    saison: "Feuillage toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau universel",
    gel: "Craint le froid (à garder > 10 °C)",
    reconnaitre: "Touffe retombante de longues frondes vert clair, finement découpées en multiples petites folioles. Port léger et arqué, très graphique.",
    entretien: "Lumière douce, jamais de soleil direct qui brûle les frondes. Aime une atmosphère humide : brumisez souvent et gardez le terreau frais. Évitez les courants d'air et l'air trop sec du chauffage."
  },

  // ===================== LOT 1 — best-sellers de pépinière =====================
  {
    nom: "Hortensia", latin: "Hydrangea macrophylla", famille: "Hortensiacées", emoji: "💙",
    photo: "hortensia.jpg", photoGrande: "hortensia.jpg",
    presentation: "Star des jardins de mi-ombre, l'hortensia offre de généreuses boules de fleurs bleues, roses ou blanches tout l'été. Sa couleur dépend de l'acidité du sol : un terrain acide donne du bleu, un sol calcaire du rose.",
    lieu: "Extérieur", soleil: "Mi-ombre", eau: "Souvent", saison: "Floraison de juin à septembre",
    floraison: "Été",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste arrondi aux grandes feuilles vertes dentées. Grosses inflorescences en boules ou en plateaux, dans les tons bleu, rose, mauve ou blanc.",
    entretien: "Aime la mi-ombre et un sol frais, riche et qui ne sèche jamais. Arrosez abondamment en été. Taillez légèrement en fin d'hiver en gardant les bourgeons. Un sol acide bleuit les fleurs."
  },
  {
    nom: "Érable du Japon", latin: "Acer palmatum", famille: "Sapindacées", emoji: "🍁",
    photo: "erable-japon.jpg", photoGrande: "erable-japon.jpg",
    presentation: "Joyau des jardins, l'érable du Japon séduit par son feuillage finement découpé qui s'embrase de rouge et d'orange en automne. Élégant et compact, il se cultive aussi très bien en grand pot.",
    lieu: "Extérieur", soleil: "Mi-ombre", eau: "Modéré", saison: "Feuillage flamboyant en automne",
    floraison: "Automne",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Petit arbre au port étalé et gracieux. Feuilles palmées à 5-7 lobes pointus, vertes, pourpres ou rouges selon la variété, virant au feu en automne.",
    entretien: "Mi-ombre à l'abri du vent et du soleil brûlant qui grille le feuillage. Sol frais, drainé, plutôt acide. Arrosez en été sans excès. Taille très légère, hors sève."
  },
  {
    nom: "Laurier-rose", latin: "Nerium oleander", famille: "Apocynacées", emoji: "🌸",
    photo: "laurier-rose.jpg", photoGrande: "laurier-rose.jpg",
    presentation: "Incontournable du Midi, le laurier-rose fleurit sans relâche tout l'été. Très résistant à la sécheresse, il fait de superbes haies et potées sur les terrasses ensoleillées. Attention : toutes ses parties sont toxiques.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Peu", saison: "Floraison de juin à octobre",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Arbuste touffu aux longues feuilles étroites, vert foncé et coriaces. Bouquets de fleurs roses, blanches, rouges ou jaunes au bout des rameaux.",
    entretien: "Plein soleil et chaleur. Très résistant à la sécheresse une fois installé. Craint le gel fort : à rentrer ou protéger en hiver. Taillez après la floraison. Toxique : à éloigner des enfants et animaux."
  },
  {
    nom: "Géranium", latin: "Pelargonium", famille: "Géraniacées", emoji: "🌺",
    photo: "geranium.jpg", photoGrande: "geranium.jpg",
    presentation: "Roi des balcons, le géranium (pélargonium) fleurit avec générosité de mai aux gelées. Facile et increvable, il colore jardinières et terrasses et n'aime rien tant que le soleil.",
    lieu: "Les deux", soleil: "Plein soleil", eau: "Modéré", saison: "Floraison de mai à octobre",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Plante touffue aux feuilles rondes et veloutées, souvent marquées d'un cercle plus foncé. Bouquets de fleurs vives, rouges, roses, blanches ou saumon.",
    entretien: "Soleil et chaleur. Laissez sécher la terre entre deux arrosages. Retirez les fleurs fanées pour relancer la floraison. Rentrez-le hors gel en hiver."
  },
  {
    nom: "Bambou", latin: "Phyllostachys aurea", famille: "Poacées", emoji: "🎍",
    photo: "bambou.jpg", photoGrande: "bambou.jpg",
    presentation: "Pour une ambiance zen et un brise-vue rapide, le bambou est imbattable. Ses cannes élancées et son feuillage bruissant au vent créent un écran végétal très décoratif. Pensez à la barrière anti-rhizome.",
    lieu: "Extérieur", soleil: "Mi-ombre", eau: "Modéré", saison: "Feuillage persistant toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Cannes creuses et ligneuses, souvent dorées ou vertes, portant un feuillage fin et léger. Pousse en touffe ou s'étale par rhizomes traçants.",
    entretien: "Soleil ou mi-ombre, sol frais. Arrosez bien la première année. Installez une barrière anti-rhizome pour les variétés traçantes, sinon il envahit. Très vigoureux."
  },
  {
    nom: "Buis", latin: "Buxus sempervirens", famille: "Buxacées", emoji: "🌳",
    photo: "buis.jpg", photoGrande: "buis.jpg",
    presentation: "Grand classique des jardins à la française, le buis se taille en boules, haies et topiaires. Son feuillage dense et persistant structure le jardin toute l'année. Surveillez la pyrale du buis.",
    lieu: "Extérieur", soleil: "Mi-ombre", eau: "Modéré", saison: "Feuillage persistant toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste très dense à petites feuilles ovales, vert foncé et luisantes. Croissance lente, se prête parfaitement à la taille en formes géométriques.",
    entretien: "Soleil ou mi-ombre, tout sol drainé. Taillez 1 à 2 fois par an pour garder la forme. Surveillez la pyrale (chenilles) et le dépérissement. Arrosage modéré."
  },
  {
    nom: "Camélia", latin: "Camellia japonica", famille: "Théacées", emoji: "🌹",
    photo: "camelia.jpg", photoGrande: "camelia.jpg",
    presentation: "Le camélia illumine la fin d'hiver de ses grandes fleurs élégantes, alors que le jardin est encore endormi. Son beau feuillage vernissé reste décoratif toute l'année à la mi-ombre.",
    lieu: "Extérieur", soleil: "Mi-ombre", eau: "Modéré", saison: "Floraison de janvier à avril",
    floraison: "Hiver",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste au feuillage persistant, vert foncé et brillant. Grandes fleurs simples ou doubles, blanches, roses ou rouges, en fin d'hiver.",
    entretien: "Mi-ombre à l'abri du soleil du matin sur le gel. Sol acide (terre de bruyère), frais et drainé. Arrosez à l'eau non calcaire. Ne taillez quasiment pas."
  },
  {
    nom: "Glycine", latin: "Wisteria sinensis", famille: "Fabacées", emoji: "💜",
    photo: "glycine.jpg", photoGrande: "glycine.jpg",
    presentation: "Reine des grimpantes, la glycine déroule au printemps de spectaculaires grappes parfumées mauves ou blanches. Vigoureuse et longévive, elle habille pergolas et façades d'une cascade fleurie.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Modéré", saison: "Floraison en avril-mai",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Plante grimpante ligneuse aux tiges torsadées très vigoureuses. Longues grappes pendantes de fleurs mauves, lilas ou blanches, parfumées.",
    entretien: "Plein soleil pour bien fleurir. Sol profond et riche. Support solide indispensable. Taillez deux fois par an (été et hiver) pour maîtriser sa vigueur et favoriser la floraison."
  },
  {
    nom: "Romarin", latin: "Salvia rosmarinus", famille: "Lamiacées", emoji: "🌿",
    photo: "romarin.jpg", photoGrande: "romarin.jpg",
    presentation: "Aromatique méditerranéenne par excellence, le romarin parfume la cuisine et le jardin toute l'année. Mellifère et résistant à la sécheresse, il se couvre de petites fleurs bleues dès la fin de l'hiver.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Peu", saison: "Floraison de février à mai",
    floraison: "Hiver",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste aux feuilles fines en aiguilles, vert foncé dessus et argentées dessous, très aromatiques. Petites fleurs bleu pâle le long des tiges.",
    entretien: "Plein soleil, sol pauvre, sec et bien drainé. Arrose très peu. Taillez légèrement après la floraison pour garder une forme compacte. Rustique et facile."
  },
  {
    nom: "Thym", latin: "Thymus vulgaris", famille: "Lamiacées", emoji: "🌱",
    photo: "thym.jpg", photoGrande: "thym.jpg",
    presentation: "Petit sous-arbrisseau de garrigue, le thym est indispensable au potager et à la cuisine. Robuste, couvre-sol et mellifère, il adore les sols secs et les rocailles ensoleillées.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Peu", saison: "Floraison de mai à juillet",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Touffe basse et compacte de minuscules feuilles aromatiques gris-vert. Petites fleurs roses ou mauves très visitées par les abeilles.",
    entretien: "Plein soleil, sol pauvre et très drainé, même caillouteux. Craint l'humidité stagnante. Arrosage quasi nul une fois installé. Taillez après floraison."
  },
  {
    nom: "Gaura", latin: "Gaura lindheimeri", famille: "Onagracées", emoji: "🦋",
    photo: "gaura.jpg", photoGrande: "gaura.jpg",
    presentation: "Légère et aérienne, la gaura danse au moindre souffle de vent avec ses nuées de petites fleurs en papillons. Florifère tout l'été et résistante à la sécheresse, elle apporte naturel et mouvement aux massifs.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Peu", saison: "Floraison de mai à octobre",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Touffe souple et buissonnante aux fines tiges arquées. Multitude de petites fleurs blanches ou roses évoquant des papillons en vol.",
    entretien: "Plein soleil, sol drainé même pauvre. Très résistante à la sécheresse. Rabattez en fin d'hiver. Floraison ininterrompue sans entretien."
  },
  {
    nom: "Agapanthe", latin: "Agapanthus africanus", famille: "Amaryllidacées", emoji: "💠",
    photo: "agapanthe.jpg", photoGrande: "agapanthe.jpg",
    presentation: "L'agapanthe dresse en plein été ses superbes boules de fleurs bleues ou blanches au-dessus d'un feuillage en lanières. Idéale en massif ou en grand pot sur une terrasse ensoleillée.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Modéré", saison: "Floraison de juin à août",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Touffe de longues feuilles rubanées vert vif. Hautes tiges nues portant une ombelle sphérique de fleurs bleues ou blanches.",
    entretien: "Plein soleil, sol drainé et riche. Arrosez en période de croissance. Protégez la souche du gel en hiver (paillage) ou rentrez les potées. Belle en pot un peu serré."
  },
  {
    nom: "Hibiscus", latin: "Hibiscus syriacus", famille: "Malvacées", emoji: "🌺",
    photo: "hibiscus.jpg", photoGrande: "hibiscus.jpg",
    presentation: "L'althéa, ou hibiscus de jardin, offre en fin d'été une profusion de grandes fleurs colorées à cœur souvent contrasté. Rustique et facile, il fait de jolies haies fleuries et des sujets isolés.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Modéré", saison: "Floraison de juillet à octobre",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste au port dressé, à feuilles dentées. Grandes fleurs en trompette, blanches, roses, mauves ou bleutées, souvent à cœur rouge.",
    entretien: "Plein soleil, tout sol drainé. Rustique et résistant. Taillez en fin d'hiver pour une floraison généreuse. Arrosage modéré, un peu plus en pot."
  },
  {
    nom: "Clématite", latin: "Clematis", famille: "Renonculacées", emoji: "💜",
    photo: "clematite.jpg", photoGrande: "clematite.jpg",
    presentation: "Grimpante préférée des jardiniers, la clématite couvre treillages et arches de grandes fleurs étoilées. Règle d'or : la tête au soleil, le pied à l'ombre et au frais.",
    lieu: "Extérieur", soleil: "Mi-ombre", eau: "Modéré", saison: "Floraison du printemps à l'automne selon variété",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Plante grimpante aux tiges fines s'accrochant par les pétioles. Grandes fleurs plates étoilées, dans toutes les teintes de blanc, rose, mauve, violet.",
    entretien: "Fleurs au soleil mais pied à l'ombre (paillez ou plantez une vivace devant). Sol frais et riche. Arrosez régulièrement. La taille dépend du groupe de la variété."
  },
  {
    nom: "Pivoine", latin: "Paeonia lactiflora", famille: "Péoniacées", emoji: "🌸",
    photo: "pivoine.jpg", photoGrande: "pivoine.jpg",
    presentation: "Symbole de romantisme, la pivoine déploie au printemps d'énormes fleurs opulentes et parfumées. Très longévive, elle peut fleurir au même endroit pendant des décennies.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Modéré", saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Touffe de feuilles découpées vert profond. Grosses fleurs simples ou doubles, blanches, roses ou rouges, souvent parfumées.",
    entretien: "Plein soleil, sol riche et profond. Ne plantez pas trop profond (sinon elle ne fleurit pas). Patiente : elle s'installe en 2-3 ans. Ne la déplacez pas."
  },
  {
    nom: "Magnolia", latin: "Magnolia × soulangeana", famille: "Magnoliacées", emoji: "🌷",
    photo: "magnolia.jpg", photoGrande: "magnolia.jpg",
    presentation: "Spectacle inoubliable du printemps, le magnolia se couvre de grandes fleurs en tulipe rose et blanc avant même les feuilles. Un arbre majestueux qui marque le réveil du jardin.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Modéré", saison: "Floraison en mars-avril",
    floraison: "Printemps",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Petit arbre au port arrondi. Grandes fleurs en coupe, rose tendre à pourpre et blanc, s'ouvrant sur les rameaux nus avant le feuillage.",
    entretien: "Soleil ou mi-ombre à l'abri des vents froids qui abîment les fleurs. Sol frais, riche, plutôt acide. Arrosez les premières années. Évitez de tailler."
  },
  {
    nom: "Palmier de Chine", latin: "Trachycarpus fortunei", famille: "Arécacées", emoji: "🌴",
    photo: "palmier.jpg", photoGrande: "palmier.jpg",
    presentation: "Le plus rustique des palmiers, le Trachycarpus apporte une touche exotique même sous les climats froids. Son stipe fibreux et ses larges palmes en éventail résistent jusqu'à -15 °C.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Modéré", saison: "Feuillage persistant toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Tronc unique couvert de fibres brunes, couronné de grandes feuilles palmées en éventail, vert foncé et rigides.",
    entretien: "Soleil ou mi-ombre, sol drainé. Arrosez bien les premières années puis il devient résistant. Rustique. Coupez les palmes sèches à la base."
  },
  {
    nom: "Citronnier", latin: "Citrus limon", famille: "Rutacées", emoji: "🍋",
    photo: "citronnier.jpg", photoGrande: "citronnier.jpg",
    presentation: "Symbole du Sud, le citronnier offre fleurs parfumées et fruits dorés une bonne partie de l'année. En pot, il s'installe sur les terrasses et passe l'hiver à l'abri du gel.",
    lieu: "Les deux", soleil: "Plein soleil", eau: "Modéré", saison: "Fleurs et fruits une grande partie de l'année",
    floraison: "Été",
    terreau: "Terreau spécial agrumes",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Petit arbre au feuillage persistant vert brillant. Fleurs blanches très parfumées, suivies de citrons jaunes.",
    entretien: "Plein soleil et chaleur. Arrosez régulièrement sans détremper, engrais agrumes en saison. Rentrez-le en véranda ou serre hors gel l'hiver. Craint le froid."
  },
  {
    nom: "Figuier", latin: "Ficus carica", famille: "Moracées", emoji: "🌳",
    photo: "figuier.jpg", photoGrande: "figuier.jpg",
    presentation: "Arbre nourricier du Midi, le figuier régale de ses fruits sucrés en fin d'été. Son large feuillage découpé crée une ombre généreuse et une vraie ambiance méditerranéenne.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Peu", saison: "Récolte des figues en été-automne",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbre au port étalé, à grandes feuilles vertes profondément découpées en lobes. Figues vertes à violettes selon la variété.",
    entretien: "Plein soleil et chaleur, sol drainé. Très résistant à la sécheresse une fois installé. Taille légère en hiver. Rustique dans la plupart des régions."
  },
  {
    nom: "Aloe vera", latin: "Aloe vera", famille: "Asphodélacées", emoji: "🌵",
    photo: "aloe-vera.jpg", photoGrande: "aloe-vera.jpg",
    presentation: "Plante grasse aux multiples vertus, l'aloe vera est aussi décorative que facile. Ses feuilles charnues stockent l'eau : on l'oublie presque ! Parfaite en pot sur un rebord ensoleillé.",
    lieu: "Les deux", soleil: "Plein soleil", eau: "Peu", saison: "Feuillage persistant toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Rosette de feuilles épaisses, charnues et dentelées sur les bords, vert glauque, remplies d'un gel translucide.",
    entretien: "Beaucoup de lumière, soleil direct progressif. Substrat très drainant (terreau cactées). Arrosez peu, seulement quand la terre est bien sèche. Craint le gel."
  },
  {
    nom: "Orchidée Phalaenopsis", latin: "Phalaenopsis", famille: "Orchidacées", emoji: "🌸",
    photo: "orchidee.jpg", photoGrande: "orchidee.jpg",
    presentation: "L'orchidée papillon est la plus facile des orchidées d'intérieur. Sa longue tige arquée de fleurs élégantes dure des semaines et refleurit chaque année avec un minimum de soins.",
    lieu: "Intérieur", soleil: "Mi-ombre", eau: "Modéré", saison: "Floraison longue, plusieurs mois",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Craint le froid (à garder > 10 °C)",
    reconnaitre: "Plante à grosses feuilles épaisses et brillantes, racines aériennes vertes. Hampe arquée portant des fleurs papillon blanches, roses ou mouchetées.",
    entretien: "Lumière vive sans soleil direct. Arrosez en trempant le pot 10 min par semaine puis laissez égoutter (jamais d'eau stagnante). Ambiance chaude et humide."
  },
  {
    nom: "Mimosa", latin: "Acacia dealbata", famille: "Fabacées", emoji: "💛",
    photo: "mimosa.jpg", photoGrande: "mimosa.jpg",
    presentation: "Soleil de l'hiver, le mimosa illumine janvier et février de ses pompons jaunes au parfum envoûtant. Vigoureux et au feuillage fin argenté, il évoque la Côte d'Azur.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Peu", saison: "Floraison en janvier-février",
    floraison: "Hiver",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Petit arbre au feuillage persistant finement découpé, vert argenté. Multitude de petits pompons jaune vif, très parfumés, en fin d'hiver.",
    entretien: "Plein soleil, sol drainé plutôt acide, à l'abri du vent froid. Craint le gel intense. Taillez après la floraison. Pousse vite."
  },
  {
    nom: "Lavande papillon", latin: "Lavandula stoechas", famille: "Lamiacées", emoji: "🦋",
    photo: "lavande-papillon.jpg", photoGrande: "lavande-papillon.jpg",
    presentation: "Cousine de la lavande vraie, la lavande papillon se reconnaît à ses épis surmontés de petites « ailes » colorées. Plus précoce, elle fleurit dès le printemps et adore la chaleur.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Peu", saison: "Floraison d'avril à juin",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Petit arbuste gris-vert aromatique. Épis floraux compacts violet foncé, coiffés de bractées en forme d'ailes de papillon mauves.",
    entretien: "Plein soleil, sol pauvre, sec et très drainé. Craint l'humidité et le calcaire. Taillez après floraison. Un peu moins rustique que la lavande vraie."
  },
  {
    nom: "Rosier grimpant", latin: "Rosa (grimpant)", famille: "Rosacées", emoji: "🌹",
    photo: "rosier-grimpant.jpg", photoGrande: "rosier-grimpant.jpg",
    presentation: "Pour habiller un mur, une pergola ou une arche, le rosier grimpant est idéal. Il déploie de longues tiges souples couvertes de fleurs parfumées, parfois remontantes jusqu'à l'automne.",
    lieu: "Extérieur", soleil: "Plein soleil", eau: "Modéré", saison: "Floraison de mai à l'automne selon variété",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Longues tiges sarmenteuses et épineuses à palisser. Fleurs simples ou doubles, en bouquets, dans toutes les couleurs, souvent parfumées.",
    entretien: "Au moins 6 h de soleil. Sol riche et drainé. Palissez les tiges à l'horizontale pour multiplier les fleurs. Taillez et retirez les fleurs fanées. Arrosez au pied."
  },

  {
    nom: "Hortensia paniculé",
    latin: "Hydrangea paniculata",
    famille: "Hortensiacées",
    emoji: "🤍",
    photo: "hortensia-panicule.jpg",
    photoGrande: "hortensia-panicule.jpg",
    presentation: "Plus solaire que l'hortensia classique, l'hortensia paniculé porte de grands cônes de fleurs blanches qui rosissent en fin de saison. Robuste et très florifère, il fleurit sur le bois de l'année.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Souvent",
    saison: "Floraison de juillet à octobre",
    floraison: "Été",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste dressé portant de grandes panicules coniques, blanc crème puis rosées. Feuilles vertes ovales et pointues.",
    entretien: "Soleil ou mi-ombre, sol frais et riche. Taillez court en fin d'hiver pour obtenir de grosses fleurs. Arrosez en été."
  },

  {
    nom: "Hortensia Annabelle",
    latin: "Hydrangea arborescens 'Annabelle'",
    famille: "Hortensiacées",
    emoji: "🤍",
    photo: "hortensia-annabelle.jpg",
    photoGrande: "hortensia-annabelle.jpg",
    presentation: "Célèbre pour ses énormes boules de fleurs blanc pur, l'hortensia 'Annabelle' illumine les coins ombragés du jardin. Spectaculaire et facile à vivre.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Souvent",
    saison: "Floraison de juin à septembre",
    floraison: "Été",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste souple aux très grosses inflorescences sphériques blanches pouvant atteindre 30 cm de diamètre.",
    entretien: "Mi-ombre, sol frais et riche qui ne sèche pas. Rabattez en fin d'hiver. Arrosez généreusement en été."
  },

  {
    nom: "Forsythia",
    latin: "Forsythia × intermedia",
    famille: "Oléacées",
    emoji: "💛",
    photo: "forsythia.jpg",
    photoGrande: "forsythia.jpg",
    presentation: "Premier feu d'artifice du printemps, le forsythia se couvre de fleurs jaune d'or avant même ses feuilles. Vigoureux et increvable, il fait de joyeuses haies.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mars-avril",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste aux longs rameaux arqués entièrement recouverts de petites fleurs jaune vif au début du printemps.",
    entretien: "Plein soleil, tout sol. Taillez juste après la floraison (il fleurit sur le bois de l'année précédente). Très rustique."
  },

  {
    nom: "Weigela",
    latin: "Weigela florida",
    famille: "Caprifoliacées",
    emoji: "🌸",
    photo: "weigela.jpg",
    photoGrande: "weigela.jpg",
    presentation: "Le weigela croule au printemps sous les clochettes roses adorées des abeilles et des papillons. Facile et généreux, parfait en massif ou en haie libre.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste au port évasé, à feuilles dentées. Nombreuses fleurs en trompette roses à rouges réparties le long des tiges.",
    entretien: "Soleil à mi-ombre, sol ordinaire. Supprimez les vieilles branches après la floraison. Arrosage modéré, rustique."
  },

  {
    nom: "Seringat",
    latin: "Philadelphus coronarius",
    famille: "Hortensiacées",
    emoji: "🤍",
    photo: "seringat.jpg",
    photoGrande: "seringat.jpg",
    presentation: "Surnommé « jasmin des poètes », le seringat embaume tout le jardin de son parfum suave à la fin du printemps. Un classique des jardins de grand-mère.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste buissonnant aux fleurs blanches simples ou doubles, très parfumées, à cœur souvent jaune.",
    entretien: "Soleil ou mi-ombre, sol ordinaire drainé. Taillez après la floraison. Rustique et sans souci."
  },

  {
    nom: "Lilas",
    latin: "Syringa vulgaris",
    famille: "Oléacées",
    emoji: "💜",
    photo: "lilas.jpg",
    photoGrande: "lilas.jpg",
    presentation: "Symbole du printemps, le lilas offre de grandes grappes mauves, violettes ou blanches au parfum inimitable. Un arbuste longévif et incontournable.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en avril-mai",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Grand arbuste aux feuilles en cœur. Grappes coniques denses de petites fleurs très parfumées, mauves à blanches.",
    entretien: "Plein soleil, sol drainé plutôt calcaire. Retirez les fleurs fanées. Taille légère après floraison. Très rustique."
  },

  {
    nom: "Spirée du Japon",
    latin: "Spiraea japonica",
    famille: "Rosacées",
    emoji: "🌸",
    photo: "spiree.jpg",
    photoGrande: "spiree.jpg",
    presentation: "Petit arbuste compact, la spirée du Japon se couvre tout l'été de plumeaux roses sur un feuillage parfois doré. Idéale en bordure ou en potée.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de juin à août",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste bas et dense à petites feuilles. Corymbes plats de minuscules fleurs roses à rouges en été.",
    entretien: "Plein soleil, tout sol. Rabattez en fin d'hiver pour une belle refloraison. Très facile et rustique."
  },

  {
    nom: "Deutzia",
    latin: "Deutzia scabra",
    famille: "Hortensiacées",
    emoji: "🤍",
    photo: "deutzia.jpg",
    photoGrande: "deutzia.jpg",
    presentation: "Discret puis éclatant, le deutzia se couvre au printemps d'une nuée de petites étoiles blanches ou rosées. Robuste et facile, parfait en haie fleurie.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste aux tiges arquées, couvert de grappes de petites fleurs étoilées blanches ou teintées de rose.",
    entretien: "Soleil ou mi-ombre, sol ordinaire. Taillez après la floraison en supprimant le vieux bois. Rustique."
  },

  {
    nom: "Viorne boule de neige",
    latin: "Viburnum opulus 'Roseum'",
    famille: "Adoxacées",
    emoji: "🤍",
    photo: "viorne-boule.jpg",
    photoGrande: "viorne-boule.jpg",
    presentation: "La viorne boule de neige doit son nom à ses grosses boules blanches qui ploient les branches au printemps. Très décorative en isolé ou en massif.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Floraison en mai",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste aux feuilles lobées comme l'érable. Grosses inflorescences sphériques blanc verdâtre puis blanc pur.",
    entretien: "Soleil ou mi-ombre, sol frais. Taille légère après floraison. Arrosez en été. Rustique et facile."
  },

  {
    nom: "Viorne tin (laurier-tin)",
    latin: "Viburnum tinus",
    famille: "Adoxacées",
    emoji: "🤍",
    photo: "viorne-tin.jpg",
    photoGrande: "viorne-tin.jpg",
    presentation: "Précieux l'hiver, le laurier-tin fleurit quand tout dort, du blanc rosé sur un feuillage toujours vert. Idéal pour des haies persistantes.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Floraison de novembre à mars",
    floraison: "Automne",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste persistant aux feuilles vert foncé. Bouquets de petites fleurs blanches issues de boutons roses, en hiver.",
    entretien: "Soleil ou mi-ombre, tout sol drainé. Très rustique et résistant. Taille légère après floraison."
  },

  {
    nom: "Abélia",
    latin: "Abelia × grandiflora",
    famille: "Caprifoliacées",
    emoji: "🤍",
    photo: "abelia.jpg",
    photoGrande: "abelia.jpg",
    presentation: "Infatigable, l'abélia fleurit de l'été à l'automne en petites clochettes parfumées sur un feuillage brillant souvent persistant. Mellifère et élégant.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de juillet à octobre",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste aux rameaux arqués, petites feuilles luisantes. Multitude de fleurs tubulaires blanc rosé, calices rougeâtres.",
    entretien: "Plein soleil, sol drainé. Taille légère en fin d'hiver. Arrosage modéré. Semi-persistant, assez rustique."
  },

  {
    nom: "Céanothe (lilas de Californie)",
    latin: "Ceanothus thyrsiflorus",
    famille: "Rhamnacées",
    emoji: "💙",
    photo: "ceanothe.jpg",
    photoGrande: "ceanothe.jpg",
    presentation: "Rare bleu intense au jardin, la céanothe se couvre au printemps de nuages de fleurs azur. Spectaculaire contre un mur chaud et ensoleillé.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste au feuillage souvent persistant, vert brillant. Grappes denses de minuscules fleurs bleu vif.",
    entretien: "Plein soleil, sol drainé, à l'abri du vent froid. Résiste à la sécheresse. Taille légère après floraison."
  },

  {
    nom: "Cognassier du Japon",
    latin: "Chaenomeles japonica",
    famille: "Rosacées",
    emoji: "🌺",
    photo: "cognassier-japon.jpg",
    photoGrande: "cognassier-japon.jpg",
    presentation: "Dès la fin de l'hiver, le cognassier du Japon allume ses fleurs rouge-orangé sur les rameaux nus. Suivent de petits coings parfumés à l'automne.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de février à avril",
    floraison: "Hiver",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste épineux aux fleurs en coupe rouges, oranges ou roses, précoces. Petits fruits jaunes parfumés.",
    entretien: "Soleil ou mi-ombre, tout sol. Taillez après la floraison. Très rustique et facile. Bon pour les confitures."
  },

  {
    nom: "Oranger du Mexique",
    latin: "Choisya ternata",
    famille: "Rutacées",
    emoji: "🤍",
    photo: "oranger-mexique.jpg",
    photoGrande: "oranger-mexique.jpg",
    presentation: "Au feuillage aromatique et persistant, l'oranger du Mexique offre des bouquets de fleurs blanches parfumées comme la fleur d'oranger. Soigné toute l'année.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Floraison en avril-mai puis remontée",
    floraison: "Printemps",
    terreau: "Terreau spécial agrumes",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste arrondi aux feuilles vert brillant divisées en trois, aromatiques. Fleurs blanches étoilées parfumées.",
    entretien: "Soleil ou mi-ombre, sol drainé, à l'abri du gel intense. Taille légère après floraison. Persistant."
  },

  {
    nom: "Arbre aux papillons",
    latin: "Buddleja davidii",
    famille: "Scrophulariacées",
    emoji: "💜",
    photo: "arbre-papillons.jpg",
    photoGrande: "arbre-papillons.jpg",
    presentation: "Véritable aimant à papillons, le buddleia déploie tout l'été de longs épis parfumés mauves, violets ou blancs. Vigoureux et increvable.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de juillet à septembre",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Grand arbuste aux longues feuilles lancéolées. Épis coniques de petites fleurs très mellifères et parfumées.",
    entretien: "Plein soleil, tout sol drainé. Rabattez sévèrement en fin d'hiver. Résiste à la sécheresse. Très rustique."
  },

  {
    nom: "Hortensia grimpant",
    latin: "Hydrangea anomala subsp. petiolaris",
    famille: "Hortensiacées",
    emoji: "🤍",
    photo: "hortensia-grimpant.jpg",
    photoGrande: "hortensia-grimpant.jpg",
    presentation: "Idéal pour habiller un mur à l'ombre, l'hortensia grimpant s'accroche seul et se couvre de larges fleurs blanches plates. Une des rares grimpantes d'ombre.",
    lieu: "Extérieur",
    soleil: "Ombre",
    eau: "Modéré",
    saison: "Floraison en juin",
    floraison: "Été",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Liane ligneuse s'accrochant par des crampons. Grandes inflorescences plates blanches en début d'été.",
    entretien: "Mi-ombre à ombre, sol frais et riche. Patient à s'installer puis vigoureux. Arrosez les premières années."
  },

  {
    nom: "Photinia Red Robin",
    latin: "Photinia × fraseri 'Red Robin'",
    famille: "Rosacées",
    emoji: "🍁",
    photo: "photinia.jpg",
    photoGrande: "photinia.jpg",
    presentation: "Star des haies modernes, le photinia 'Red Robin' éclate de jeunes pousses rouge vif au printemps sur un feuillage persistant. Décoratif toute l'année.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Jeunes pousses rouges au printemps",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste persistant aux feuilles brillantes, rouge éclatant quand elles sont jeunes puis vert foncé.",
    entretien: "Soleil ou mi-ombre, sol drainé. Taillez 1 à 2 fois par an pour relancer les pousses rouges. Rustique."
  },

  {
    nom: "Millepertuis",
    latin: "Hypericum 'Hidcote'",
    famille: "Hypéricacées",
    emoji: "💛",
    photo: "millepertuis.jpg",
    photoGrande: "millepertuis.jpg",
    presentation: "Couvre-sol robuste, le millepertuis illumine l'été de grandes fleurs jaune d'or à étamines en pinceau. Idéal sur talus et zones difficiles.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de juin à septembre",
    floraison: "Été",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste bas et dense. Grandes fleurs jaune vif à nombreuses étamines, longue floraison estivale.",
    entretien: "Soleil ou mi-ombre, tout sol. Rabattez en fin d'hiver. Résiste à la sécheresse. Très facile."
  },

  {
    nom: "Cytise",
    latin: "Laburnum anagyroides",
    famille: "Fabacées",
    emoji: "💛",
    photo: "cytise.jpg",
    photoGrande: "cytise.jpg",
    presentation: "Au printemps, le cytise déroule de spectaculaires grappes pendantes jaune d'or, comme des cascades. Magnifique mais attention : ses graines sont toxiques.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mai",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Petit arbre aux longues grappes pendantes de fleurs jaunes parfumées. Feuilles à trois folioles.",
    entretien: "Plein soleil, sol drainé. Taille minimale. Rustique. Toxique : éloignez les enfants des gousses et graines."
  },

  {
    nom: "Groseillier à fleurs",
    latin: "Ribes sanguineum",
    famille: "Grossulariacées",
    emoji: "🌸",
    photo: "groseillier-fleurs.jpg",
    photoGrande: "groseillier-fleurs.jpg",
    presentation: "Annonciateur du printemps, le groseillier à fleurs se pare de grappes roses retombantes très tôt en saison. Facile et mellifère, parfait en haie.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mars-avril",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Arbuste aux feuilles lobées aromatiques. Grappes pendantes de petites fleurs rose vif au début du printemps.",
    entretien: "Soleil ou mi-ombre, tout sol. Taillez après la floraison. Très rustique et sans entretien."
  },

  {
    nom: "Laurier-sauce",
    latin: "Laurus nobilis",
    famille: "Lauracées",
    emoji: "🌿",
    photo: "laurier-sauce.jpg",
    photoGrande: "laurier-sauce.jpg",
    presentation: "Le laurier noble parfume la cuisine et structure le jardin. Persistant et taillable, il se cultive en haie, en boule ou en pot sur une terrasse.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Feuillage persistant toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste aux feuilles vert foncé, coriaces et aromatiques, utilisées en cuisine. Petites fleurs jaunâtres.",
    entretien: "Soleil ou mi-ombre, sol drainé. Résiste à la sécheresse. Se taille bien. Craint le gel intense en jeune sujet."
  },

  {
    nom: "Cyprès de Provence",
    latin: "Cupressus sempervirens",
    famille: "Cupressacées",
    emoji: "🌲",
    photo: "cypres-provence.jpg",
    photoGrande: "cypres-provence.jpg",
    presentation: "Silhouette emblématique du paysage méditerranéen, le cyprès de Provence dresse sa flamme verte vers le ciel. Élégant en alignement ou en isolé.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Feuillage persistant toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Conifère à port colonnaire très étroit et dressé, feuillage persistant vert sombre en écailles.",
    entretien: "Plein soleil, sol drainé. Très résistant à la sécheresse. Rustique. Aucune taille nécessaire."
  },

  {
    nom: "Pittosporum",
    latin: "Pittosporum tobira",
    famille: "Pittosporacées",
    emoji: "🤍",
    photo: "pittosporum.jpg",
    photoGrande: "pittosporum.jpg",
    presentation: "Le pittosporum séduit par son feuillage dense et brillant et ses fleurs crème au parfum de fleur d'oranger. Parfait en haie de bord de mer.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison au printemps",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste compact aux feuilles vert luisant en rosettes. Petites fleurs blanc crème très parfumées au printemps.",
    entretien: "Plein soleil, sol drainé. Résiste à la sécheresse et aux embruns. Se taille bien. Craint le gel sévère."
  },

  {
    nom: "Arbousier",
    latin: "Arbutus unedo",
    famille: "Éricacées",
    emoji: "🍓",
    photo: "arbousier.jpg",
    photoGrande: "arbousier.jpg",
    presentation: "Curiosité du jardin méditerranéen, l'arbousier porte en même temps fleurs blanches et fruits rouges comestibles en automne. Persistant et décoratif.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Fleurs et fruits en automne",
    floraison: "Automne",
    terreau: "Terre de bruyère (sol acide)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste à écorce rougeâtre et feuilles persistantes brillantes. Clochettes blanches et fruits ronds rouges granuleux.",
    entretien: "Plein soleil, sol drainé acide. Résiste à la sécheresse. Rustique. Taille légère seulement."
  },

  {
    nom: "Grenadier",
    latin: "Punica granatum",
    famille: "Lythracées",
    emoji: "🌺",
    photo: "grenadier.jpg",
    photoGrande: "grenadier.jpg",
    presentation: "Le grenadier offre de flamboyantes fleurs orange vif en été, puis ses fameuses grenades à l'automne. Une touche d'exotisme résistante à la sécheresse.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Fleurs en été, fruits en automne",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Arbuste aux fleurs en trompette rouge-orangé éclatant. Gros fruits ronds à écorce coriace renfermant des grains rouges.",
    entretien: "Plein soleil et chaleur, sol drainé. Très résistant à la sécheresse. Craint le gel intense. Taille légère."
  },

  {
    nom: "Bougainvillier",
    latin: "Bougainvillea glabra",
    famille: "Nyctaginacées",
    emoji: "💜",
    photo: "bougainvillier.jpg",
    photoGrande: "bougainvillier.jpg",
    presentation: "Explosion de couleurs du Sud, le bougainvillier couvre murs et pergolas de bractées fuchsia, orange ou blanches tout l'été. À rentrer hors gel.",
    lieu: "Les deux",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de mai à octobre",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Grimpante ligneuse et épineuse. Vraies fleurs minuscules entourées de bractées papier très colorées.",
    entretien: "Plein soleil et chaleur, sol drainé. Arrosez peu. Rentrez-le en hiver hors gel (véranda). Palissez les tiges."
  },

  {
    nom: "Jasmin étoilé",
    latin: "Trachelospermum jasminoides",
    famille: "Apocynacées",
    emoji: "🤍",
    photo: "jasmin-etoile.jpg",
    photoGrande: "jasmin-etoile.jpg",
    presentation: "Grimpante persistante au parfum envoûtant, le jasmin étoilé couvre treillages et pergolas d'étoiles blanches tout l'été. Élégant et facile.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de juin à août",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Liane au feuillage persistant vert foncé luisant. Petites fleurs blanches en hélice, très parfumées.",
    entretien: "Soleil ou mi-ombre, sol drainé. Support nécessaire. Assez rustique une fois installé. Taille légère après floraison."
  },

  {
    nom: "Eleagnus",
    latin: "Elaeagnus × ebbingei",
    famille: "Éléagnacées",
    emoji: "🌿",
    photo: "eleagnus.jpg",
    photoGrande: "eleagnus.jpg",
    presentation: "Robuste et persistant, l'eleagnus fait des haies brise-vent infaillibles, même en bord de mer. Ses petites fleurs d'automne embaument discrètement.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Feuillage persistant, parfum en automne",
    floraison: "Automne",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Arbuste vigoureux aux feuilles persistantes vert argenté, revers écailleux. Petites fleurs crème parfumées en automne.",
    entretien: "Soleil ou mi-ombre, tout sol. Résiste à la sécheresse, au vent et aux embruns. Se taille très bien. Rustique."
  },

  {
    nom: "Phormium (lin de Nouvelle-Zélande)",
    latin: "Phormium tenax",
    famille: "Asphodélacées",
    emoji: "🌿",
    photo: "phormium.jpg",
    photoGrande: "phormium.jpg",
    presentation: "Très architectural, le phormium dresse en touffe ses longues feuilles rubanées, vertes, pourpres ou panachées. Une touche exotique et moderne.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Feuillage graphique toute l'année",
    floraison: "Toute l'année",
    terreau: "Terreau universel",
    gel: "Peu rustique (−5 à −10 °C)",
    reconnaitre: "Grande touffe de feuilles coriaces dressées en lanières, vertes à pourpres ou bicolores selon la variété.",
    entretien: "Plein soleil, sol drainé. Arrosage modéré. Protégez du gel intense (paillage) ou cultivez en pot à rentrer."
  },

  {
    nom: "Yucca",
    latin: "Yucca gloriosa",
    famille: "Asphodélacées",
    emoji: "🌵",
    photo: "yucca-gloriosa.jpg",
    photoGrande: "yucca-gloriosa.jpg",
    presentation: "Sculptural et résistant, le yucca dresse ses rosettes de feuilles pointues et, l'été, de hautes hampes de clochettes blanches. Style exotique garanti.",
    lieu: "Les deux",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison estivale",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Rosette de feuilles rigides en glaive, vert bleuté. Grande hampe florale dressée portant des clochettes blanc crème.",
    entretien: "Plein soleil, sol très drainé. Résiste à la sécheresse. Rustique. Arrosez peu. Attention aux pointes piquantes."
  },

  {
    nom: "Échinacée",
    latin: "Echinacea purpurea",
    famille: "Astéracées",
    emoji: "🌸",
    photo: "echinacee.jpg",
    photoGrande: "echinacee.jpg",
    presentation: "Star des massifs naturels, l'échinacée dresse ses grandes marguerites roses à cône bombé, adorées des papillons. Robuste et longue à fleurir.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de juillet à septembre",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace dressée aux grandes fleurs roses-pourpres à cœur orangé saillant, en forme de cône.",
    entretien: "Plein soleil, sol drainé. Résiste bien à la sécheresse. Rabattez en fin d'hiver. Mellifère et rustique."
  },

  {
    nom: "Rudbeckia",
    latin: "Rudbeckia fulgida",
    famille: "Astéracées",
    emoji: "💛",
    photo: "rudbeckia.jpg",
    photoGrande: "rudbeckia.jpg",
    presentation: "Soleil du jardin de fin d'été, le rudbeckia couvre les massifs de marguerites jaune d'or à cœur noir. Généreux, lumineux et increvable.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de juillet à octobre",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace touffue aux nombreuses fleurs jaune vif à cœur brun-noir bombé. Longue floraison.",
    entretien: "Plein soleil, sol ordinaire frais. Rabattez en fin d'hiver. Très rustique et facile. Mellifère."
  },

  {
    nom: "Hémérocalle (lis d'un jour)",
    latin: "Hemerocallis hybrida",
    famille: "Asphodélacées",
    emoji: "🧡",
    photo: "hemerocalle.jpg",
    photoGrande: "hemerocalle.jpg",
    presentation: "Increvable et florifère, l'hémérocalle offre chaque jour de nouvelles fleurs en trompette, dans toutes les couleurs. Une vivace sans souci par excellence.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de juin à août",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Touffe de feuilles rubanées arquées. Grandes fleurs en trompette éphémères (un jour), renouvelées sans cesse.",
    entretien: "Soleil ou mi-ombre, tout sol. Très tolérante. Rabattez le feuillage en automne. Rustique et facile."
  },

  {
    nom: "Heuchère",
    latin: "Heuchera sanguinea",
    famille: "Saxifragacées",
    emoji: "🍂",
    photo: "heuchere.jpg",
    photoGrande: "heuchere.jpg",
    presentation: "Cultivée surtout pour son feuillage spectaculaire (pourpre, caramel, lime…), l'heuchère habille les bordures d'ombre toute l'année. Petites fleurs en clochettes.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Feuillage coloré + floraison printemps-été",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace en touffe de feuilles lobées très colorées. Fines hampes de minuscules clochettes au printemps.",
    entretien: "Mi-ombre, sol frais et drainé. Persistante. Divisez tous les 3 ans. Arrosage modéré. Rustique."
  },

  {
    nom: "Hosta",
    latin: "Hosta sieboldiana",
    famille: "Asparagacées",
    emoji: "🍃",
    photo: "hosta.jpg",
    photoGrande: "hosta.jpg",
    presentation: "Reine des jardins d'ombre, l'hosta déploie de larges feuilles graphiques, vertes, bleutées ou panachées. Un feuillage somptueux pour les coins frais.",
    lieu: "Extérieur",
    soleil: "Ombre",
    eau: "Souvent",
    saison: "Beau feuillage d'avril à octobre",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Touffe de grandes feuilles nervurées en cœur, vert bleuté à panaché. Hampes de fleurs lilas en été.",
    entretien: "Ombre à mi-ombre, sol frais et riche. Arrosez en été. Surveillez les limaces. Rustique, disparaît l'hiver."
  },

  {
    nom: "Sauge des bois",
    latin: "Salvia nemorosa",
    famille: "Lamiacées",
    emoji: "💜",
    photo: "sauge-bois.jpg",
    photoGrande: "sauge-bois.jpg",
    presentation: "Pilier des massifs naturalistes, la sauge des bois dresse de longs épis violets très mellifères tout l'été. Sobre, résistante et infatigable.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de mai à septembre",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Vivace touffue à tiges carrées. Épis dressés de petites fleurs violet intense, longue floraison.",
    entretien: "Plein soleil, sol drainé. Résiste à la sécheresse. Rabattez après la 1re floraison pour une remontée. Rustique."
  },

  {
    nom: "Népéta (herbe à chat)",
    latin: "Nepeta × faassenii",
    famille: "Lamiacées",
    emoji: "💙",
    photo: "nepeta.jpg",
    photoGrande: "nepeta.jpg",
    presentation: "Nuage bleu-mauve adoré des abeilles (et des chats !), la népéta borde allées et massifs d'un flot de fleurs tout l'été. Aromatique et sans entretien.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de mai à septembre",
    floraison: "Printemps",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace souple au feuillage gris-vert aromatique. Multitude de petites fleurs bleu-mauve en épis lâches.",
    entretien: "Plein soleil, sol drainé. Très résistante à la sécheresse. Rabattez après la première vague de fleurs. Rustique."
  },

  {
    nom: "Achillée",
    latin: "Achillea millefolium",
    famille: "Astéracées",
    emoji: "🌼",
    photo: "achillee.jpg",
    photoGrande: "achillee.jpg",
    presentation: "Plate et graphique, l'achillée porte de larges ombelles colorées sur un feuillage finement découpé. Mellifère, résistante et idéale en prairie fleurie.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de juin à septembre",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace au feuillage très découpé. Larges corymbes plats de petites fleurs, jaunes, roses, rouges ou blanches.",
    entretien: "Plein soleil, sol drainé même pauvre. Très résistante à la sécheresse. Rabattez en fin d'hiver. Rustique."
  },

  {
    nom: "Delphinium (pied d'alouette)",
    latin: "Delphinium elatum",
    famille: "Renonculacées",
    emoji: "💙",
    photo: "delphinium.jpg",
    photoGrande: "delphinium.jpg",
    presentation: "Majestueux, le delphinium dresse de hautes colonnes de fleurs bleues spectaculaires au cœur de l'été. L'âme des jardins anglais.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en juin-juillet",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace à hautes hampes dressées garnies de grandes fleurs bleu intense (ou mauves, blanches).",
    entretien: "Plein soleil, sol riche et frais. Tuteurez les hampes. Rabattez après floraison pour une remontée. Rustique."
  },

  {
    nom: "Lupin",
    latin: "Lupinus polyphyllus",
    famille: "Fabacées",
    emoji: "💜",
    photo: "lupin.jpg",
    photoGrande: "lupin.jpg",
    presentation: "Le lupin élève au-dessus de son feuillage palmé de superbes épis dressés bicolores. Une vivace généreuse qui enrichit même le sol en azote.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace à feuilles palmées caractéristiques. Grands épis dressés de fleurs papilionacées, souvent bicolores.",
    entretien: "Plein soleil, sol drainé plutôt acide. Coupez les épis fanés. Arrosage modéré. Rustique, parfois éphémère."
  },

  {
    nom: "Géranium vivace",
    latin: "Geranium macrorrhizum",
    famille: "Géraniacées",
    emoji: "🌸",
    photo: "geranium-vivace.jpg",
    photoGrande: "geranium-vivace.jpg",
    presentation: "À ne pas confondre avec le géranium de balcon, le géranium vivace est un couvre-sol increvable au feuillage aromatique qui étouffe les mauvaises herbes.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Peu",
    saison: "Floraison de mai à juillet",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Rustique (−10 à −15 °C)",
    reconnaitre: "Vivace tapissante au feuillage parfumé. Petites fleurs à cinq pétales roses, mauves ou blanches.",
    entretien: "Soleil ou mi-ombre, tout sol. Très résistant à la sécheresse et sans entretien. Se ressème seul. Rustique."
  },

  {
    nom: "Astilbe",
    latin: "Astilbe × arendsii",
    famille: "Saxifragacées",
    emoji: "🌸",
    photo: "astilbe.jpg",
    photoGrande: "astilbe.jpg",
    presentation: "Pour les coins frais et ombragés, l'astilbe dresse de légers plumeaux roses, rouges ou blancs au-dessus d'un feuillage découpé. Douceur garantie.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Souvent",
    saison: "Floraison de juin à août",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace au feuillage finement découpé. Panicules plumeuses dressées de minuscules fleurs duveteuses.",
    entretien: "Mi-ombre à ombre, sol frais qui ne sèche JAMAIS. Arrosez beaucoup en été. Rustique, disparaît l'hiver."
  },

  {
    nom: "Anémone du Japon",
    latin: "Anemone hupehensis",
    famille: "Renonculacées",
    emoji: "🌸",
    photo: "anemone-japon.jpg",
    photoGrande: "anemone-japon.jpg",
    presentation: "Grâce et légèreté à l'automne : l'anémone du Japon danse sur de fines tiges, ses fleurs roses ou blanches éclairant le jardin quand l'été décline.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Floraison de août à octobre",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace dressée portant de longues tiges souples coiffées de fleurs simples roses ou blanches à cœur jaune.",
    entretien: "Mi-ombre, sol frais et riche. Patiente à s'installer puis vigoureuse. Arrosez en été. Rustique."
  },

  {
    nom: "Aster d'automne",
    latin: "Symphyotrichum novae-angliae",
    famille: "Astéracées",
    emoji: "💜",
    photo: "aster-automne.jpg",
    photoGrande: "aster-automne.jpg",
    presentation: "Bouquet final du jardin, l'aster d'automne se couvre de centaines de petites marguerites mauves quand presque tout est fané. Festin pour les abeilles.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de septembre à octobre",
    floraison: "Automne",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace dressée et touffue, couverte en automne d'une multitude de petites fleurs étoilées mauves à cœur jaune.",
    entretien: "Plein soleil, sol frais. Rabattez en fin d'hiver. Tuteurez les variétés hautes. Très rustique et mellifère."
  },

  {
    nom: "Coréopsis",
    latin: "Coreopsis grandiflora",
    famille: "Astéracées",
    emoji: "💛",
    photo: "coreopsis.jpg",
    photoGrande: "coreopsis.jpg",
    presentation: "Soleil miniature, le coréopsis sème la lumière dans les massifs tout l'été avec ses petites marguerites jaune d'or. Joyeux, sobre et infatigable.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de juin à septembre",
    floraison: "Été",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace légère et ramifiée. Profusion de petites fleurs jaune vif à long pédoncule, longue floraison.",
    entretien: "Plein soleil, sol drainé même pauvre. Résiste à la sécheresse. Retirez les fleurs fanées. Rustique."
  },

  {
    nom: "Ancolie",
    latin: "Aquilegia vulgaris",
    famille: "Renonculacées",
    emoji: "💜",
    photo: "ancolie.jpg",
    photoGrande: "ancolie.jpg",
    presentation: "Délicate et champêtre, l'ancolie porte d'élégantes fleurs éperonnées qui semblent suspendues. Elle se ressème seule et s'installe avec grâce.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace au feuillage découpé bleuté. Fleurs pendantes à éperons, bleues, mauves, roses ou blanches.",
    entretien: "Mi-ombre, sol frais et drainé. Se ressème spontanément. Peu exigeante. Rustique, parfois éphémère."
  },

  {
    nom: "Orpin d'automne",
    latin: "Hylotelephium spectabile",
    famille: "Crassulacées",
    emoji: "🌸",
    photo: "orpin.jpg",
    photoGrande: "orpin.jpg",
    presentation: "Plante grasse rustique, l'orpin d'automne forme de larges plateaux roses qui virent au cuivre, très visités par les abeilles à l'arrière-saison.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Peu",
    saison: "Floraison de septembre à octobre",
    floraison: "Automne",
    terreau: "Terreau drainant (méditerranéen/cactées)",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace charnue aux feuilles épaisses gris-vert. Larges corymbes plats de petites fleurs roses, mellifères.",
    entretien: "Plein soleil, sol drainé. Très résistant à la sécheresse, increvable. Rabattez en fin d'hiver. Rustique."
  },

  {
    nom: "Bergénia (plante des savetiers)",
    latin: "Bergenia cordifolia",
    famille: "Saxifragacées",
    emoji: "🌸",
    photo: "bergenia.jpg",
    photoGrande: "bergenia.jpg",
    presentation: "Couvre-sol persistant et costaud, le bergénia déploie de grandes feuilles luisantes et des grappes roses dès la fin de l'hiver. Increvable, même à l'ombre.",
    lieu: "Extérieur",
    soleil: "Mi-ombre",
    eau: "Modéré",
    saison: "Floraison en mars-avril",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace aux grandes feuilles arrondies, épaisses et persistantes, rougissant l'hiver. Grappes de fleurs roses.",
    entretien: "Soleil ou ombre, tout sol. Très tolérant et sans entretien. Persistant. Divisez si nécessaire. Rustique."
  },

  {
    nom: "Grande marguerite",
    latin: "Leucanthemum × superbum",
    famille: "Astéracées",
    emoji: "🤍",
    photo: "marguerite.jpg",
    photoGrande: "marguerite.jpg",
    presentation: "Indémodable, la grande marguerite illumine les massifs de ses grandes fleurs blanches à cœur d'or tout l'été. Simple, généreuse et facile à vivre.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison de juin à août",
    floraison: "Été",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace dressée aux grandes fleurs blanches classiques à cœur jaune, sur de longues tiges.",
    entretien: "Plein soleil, sol ordinaire drainé. Retirez les fleurs fanées. Divisez tous les 3 ans. Très rustique."
  },

  {
    nom: "Pavot d'Orient",
    latin: "Papaver orientale",
    famille: "Papavéracées",
    emoji: "🧡",
    photo: "pavot-orient.jpg",
    photoGrande: "pavot-orient.jpg",
    presentation: "Spectaculaire et éphémère, le pavot d'Orient ouvre au printemps d'immenses fleurs froissées rouge orangé à cœur noir. Un coup d'éclat inoubliable au jardin.",
    lieu: "Extérieur",
    soleil: "Plein soleil",
    eau: "Modéré",
    saison: "Floraison en mai-juin",
    floraison: "Printemps",
    terreau: "Terreau universel",
    gel: "Très rustique (−15 à −25 °C)",
    reconnaitre: "Vivace au feuillage velu et découpé. Très grandes fleurs en coupe rouge-orangé vif à macule noire, aux pétales froissés comme du papier de soie.",
    entretien: "Plein soleil, sol drainé. Le feuillage disparaît après la floraison (c'est normal) : rabattez alors. Résiste bien à la sécheresse. Rustique."
  }
];
