/* ============================================================
   TAILLE ADULTE (hauteur × largeur à maturité) — valeurs uniques
   approximatives, pour rester lisible. Chargé après les données.
   ============================================================ */
(function () {
  if (typeof PLANTES === "undefined") return;
  // nom : [hauteur, largeur] (approx.)
  const TAILLES = {
    "Lavande": ["50 cm", "70 cm"],
    "Olivier": ["6 m", "4 m"],
    "Monstera": ["2,5 m", "1,5 m"],
    "Rosier": ["1 m", "80 cm"],
    "Basilic": ["40 cm", "30 cm"],
    "Fougère de Boston": ["60 cm", "70 cm"],
    "Hortensia": ["1,2 m", "1,2 m"],
    "Érable du Japon": ["3 m", "2,5 m"],
    "Laurier-rose": ["2,5 m", "2 m"],
    "Géranium": ["40 cm", "35 cm"],
    "Bambou": ["3 m", "1,5 m"],
    "Buis": ["1,5 m", "1 m"],
    "Camélia": ["2 m", "2 m"],
    "Glycine": ["8 m", "6 m"],
    "Romarin": ["1,2 m", "1,2 m"],
    "Thym": ["25 cm", "35 cm"],
    "Gaura": ["80 cm", "60 cm"],
    "Agapanthe": ["80 cm", "50 cm"],
    "Hibiscus": ["2,5 m", "1,8 m"],
    "Clématite": ["3 m", "1,2 m"],
    "Pivoine": ["90 cm", "90 cm"],
    "Magnolia": ["6 m", "4 m"],
    "Palmier de Chine": ["4 m", "2,5 m"],
    "Citronnier": ["3 m", "2 m"],
    "Figuier": ["4 m", "4 m"],
    "Aloe vera": ["50 cm", "50 cm"],
    "Orchidée Phalaenopsis": ["50 cm", "25 cm"],
    "Mimosa": ["6 m", "4 m"],
    "Lavande papillon": ["60 cm", "65 cm"],
    "Rosier grimpant": ["3 m", "2 m"],
    "Hortensia paniculé": ["2 m", "1,8 m"],
    "Hortensia Annabelle": ["1,2 m", "1,2 m"],
    "Forsythia": ["2,5 m", "2,5 m"],
    "Weigela": ["2 m", "2 m"],
    "Seringat": ["2,5 m", "2,5 m"],
    "Lilas": ["4 m", "3 m"],
    "Spirée du Japon": ["90 cm", "90 cm"],
    "Deutzia": ["2 m", "1,8 m"],
    "Viorne boule de neige": ["3,5 m", "2,5 m"],
    "Viorne tin (laurier-tin)": ["2,5 m", "2,5 m"],
    "Abélia": ["1,5 m", "2 m"],
    "Céanothe (lilas de Californie)": ["2 m", "2 m"],
    "Cognassier du Japon": ["1,5 m", "1,8 m"],
    "Oranger du Mexique": ["2 m", "2 m"],
    "Arbre aux papillons": ["2,5 m", "2,5 m"],
    "Hortensia grimpant": ["7 m", "2,5 m"],
    "Photinia Red Robin": ["3 m", "2,5 m"],
    "Millepertuis": ["80 cm", "80 cm"],
    "Cytise": ["4 m", "3,5 m"],
    "Groseillier à fleurs": ["2 m", "1,8 m"],
    "Laurier-sauce": ["4 m", "3 m"],
    "Cyprès de Provence": ["15 m", "1,5 m"],
    "Pittosporum": ["3 m", "2 m"],
    "Arbousier": ["4 m", "3,5 m"],
    "Grenadier": ["3 m", "2,5 m"],
    "Bougainvillier": ["4 m", "3 m"],
    "Jasmin étoilé": ["4 m", "2 m"],
    "Eleagnus": ["3 m", "3 m"],
    "Phormium (lin de Nouvelle-Zélande)": ["1,5 m", "1,5 m"],
    "Yucca": ["2 m", "1,2 m"],
    "Échinacée": ["80 cm", "45 cm"],
    "Rudbeckia": ["80 cm", "50 cm"],
    "Hémérocalle (lis d'un jour)": ["65 cm", "60 cm"],
    "Heuchère": ["40 cm", "40 cm"],
    "Hosta": ["60 cm", "80 cm"],
    "Sauge des bois": ["50 cm", "45 cm"],
    "Népéta (herbe à chat)": ["45 cm", "50 cm"],
    "Achillée": ["80 cm", "50 cm"],
    "Delphinium (pied d'alouette)": ["1,4 m", "50 cm"],
    "Lupin": ["1 m", "50 cm"],
    "Géranium vivace": ["40 cm", "50 cm"],
    "Astilbe": ["60 cm", "50 cm"],
    "Anémone du Japon": ["1 m", "50 cm"],
    "Aster d'automne": ["90 cm", "50 cm"],
    "Coréopsis": ["55 cm", "45 cm"],
    "Ancolie": ["55 cm", "35 cm"],
    "Orpin d'automne": ["50 cm", "45 cm"],
    "Bergénia (plante des savetiers)": ["40 cm", "50 cm"],
    "Grande marguerite": ["75 cm", "50 cm"],
    "Pavot d'Orient": ["75 cm", "60 cm"],
    "Figuier lyre": ["2 m", "80 cm"],
    "Caoutchouc": ["2 m", "80 cm"],
    "Pothos": ["1,5 m", "30 cm"],
    "Sansevière": ["70 cm", "30 cm"],
    "Zamioculcas": ["80 cm", "65 cm"],
    "Fleur de lune": ["55 cm", "50 cm"],
    "Calathéa": ["65 cm", "60 cm"],
    "Dracaena de Madagascar": ["1,5 m", "50 cm"],
    "Aglaonéma": ["50 cm", "50 cm"],
    "Dieffenbachia": ["1 m", "65 cm"],
    "Philodendron grimpant": ["1,5 m", "40 cm"],
    "Anthurium": ["50 cm", "35 cm"],
    "Croton": ["90 cm", "50 cm"],
    "Schefflera": ["1,5 m", "80 cm"],
    "Palmier areca": ["2 m", "1 m"],
    "Palmier kentia": ["2,5 m", "1,2 m"],
    "Aspidistra": ["60 cm", "60 cm"],
    "Maranta": ["25 cm", "35 cm"],
    "Arbre de jade": ["80 cm", "50 cm"],
    "Échévéria": ["12 cm", "20 cm"],
    "Kalanchoé": ["30 cm", "25 cm"],
    "Cactus de Noël": ["25 cm", "35 cm"],
    "Haworthia": ["10 cm", "10 cm"],
    "Aéonium": ["60 cm", "40 cm"],
    "Plante araignée": ["30 cm", "40 cm"],
    "Misère": ["15 cm", "30 cm"],
    "Bégonia maculé": ["60 cm", "35 cm"],
    "Violette africaine": ["12 cm", "18 cm"],
    "Fittonia": ["12 cm", "25 cm"],
    "Pépéromia": ["25 cm", "25 cm"],
    "Fleur de porcelaine": ["1,5 m", "40 cm"],
    "Fougère nid d'oiseau": ["75 cm", "65 cm"],
    "Piléa": ["25 cm", "25 cm"],
    "Alocasia": ["75 cm", "65 cm"],
    "Oiseau de paradis": ["1,8 m", "1 m"],
    "Tulipe": ["40 cm", "12 cm"],
    "Narcisse": ["35 cm", "12 cm"],
    "Jacinthe": ["25 cm", "12 cm"],
    "Crocus": ["12 cm", "6 cm"],
    "Iris des jardins": ["80 cm", "35 cm"],
    "Muguet": ["20 cm", "30 cm"],
    "Perce-neige": ["12 cm", "6 cm"],
    "Dahlia": ["80 cm", "50 cm"],
    "Glaïeul": ["1,2 m", "18 cm"],
    "Bégonia tubéreux": ["30 cm", "25 cm"],
    "Œillet": ["45 cm", "30 cm"],
    "Primevère": ["15 cm", "20 cm"],
    "Pensée": ["20 cm", "20 cm"],
    "Souci": ["40 cm", "30 cm"],
    "Capucine": ["30 cm", "40 cm"],
    "Tournesol": ["2 m", "50 cm"],
    "Cosmos": ["1 m", "40 cm"],
    "Zinnia": ["60 cm", "30 cm"],
    "Pétunia": ["30 cm", "40 cm"],
    "Muflier": ["55 cm", "30 cm"],
    "Lis blanc": ["1,2 m", "25 cm"],
    "Renoncule": ["30 cm", "18 cm"],
    "Anémone de Caen": ["30 cm", "18 cm"],
    "Crocosmia": ["80 cm", "25 cm"],
    "Ail d'ornement": ["1,2 m", "20 cm"],
    "Rhododendron": ["2 m", "2 m"],
    "Azalée": ["1 m", "90 cm"],
    "Bruyère": ["30 cm", "40 cm"],
    "Skimmia": ["90 cm", "90 cm"],
    "Piéris du Japon": ["1,8 m", "1,5 m"],
    "Mahonia": ["1,5 m", "1,2 m"],
    "Houx": ["4 m", "3 m"],
    "Fusain du Japon": ["1,8 m", "1,5 m"],
    "Troène": ["3 m", "2 m"],
    "Cornouiller blanc": ["2,5 m", "2,5 m"],
    "Sureau noir": ["4 m", "3 m"],
    "Aubépine": ["5 m", "4 m"],
    "Chèvrefeuille": ["4 m", "2 m"],
    "Passiflore": ["6 m", "2 m"],
    "Jasmin d'hiver": ["2,5 m", "2 m"],
    "Lierre": ["15 m", "3 m"],
    "Vigne vierge": ["15 m", "4 m"],
    "Laurier du Portugal": ["4 m", "3 m"],
    "Eucalyptus": ["12 m", "6 m"],
    "Cornouiller du Japon": ["5 m", "4 m"],
    "Cerisier du Japon": ["6 m", "5 m"],
    "Ginkgo": ["20 m", "10 m"],
    "Bouleau": ["20 m", "6 m"],
    "Saule pleureur": ["10 m", "10 m"],
    "Tilleul": ["20 m", "10 m"],
    "Marronnier": ["25 m", "12 m"],
    "Catalpa": ["12 m", "8 m"],
    "Pin parasol": ["15 m", "10 m"],
    "If commun": ["8 m", "5 m"],
    "Érable champêtre": ["12 m", "8 m"],
    "Tomate": ["1,5 m", "50 cm"],
    "Menthe": ["45 cm", "50 cm"],
    "Persil": ["30 cm", "25 cm"],
    "Ciboulette": ["28 cm", "25 cm"],
    "Sauge officinale": ["55 cm", "65 cm"],
    "Origan": ["45 cm", "40 cm"],
    "Fraisier": ["25 cm", "30 cm"],
    "Courgette": ["60 cm", "1,2 m"],
    "Fenouil": ["1,5 m", "50 cm"],
    "Estragon": ["80 cm", "45 cm"],
  };

  PLANTES.forEach(p => {
    const t = TAILLES[p.nom];
    if (t) { p.hauteur = t[0]; p.largeur = t[1]; }
  });
})();
